### ISSUE TITLE
Segmentation fault: 11 on macOS 10.14, codesign --deep should probably be the final step in install.sh

### ISSUE THREAD

**Issue by briankendall** [r1olo/spotify-adblock-macos#4]
After running `install.sh`, Spotify can't run and crashes with `Segmentation fault: 11`. This seems to be caused by its signature no longer being valid. I think the order of operations in `install.sh` is incorrect.

Rather than being this:

    gcc -dynamiclib -o "Chromium Embedded Framework" spotiblock.c &&
    codesign --force --deep --sign "$cert" "$path" &&
    codesign --sign "$cert" "Chromium Embedded Framework" &&
    mv -v "$libpath/Chromium Embedded Framework"{,.orig} &&
    mv -v "Chromium Embedded Framework" "$libpath"

It should be this:

    gcc -dynamiclib -o "Chromium Embedded Framework" spotiblock.c &&
    codesign --sign "$cert" "Chromium Embedded Framework" &&
    mv -v "$libpath/Chromium Embedded Framework"{,.orig} &&
    mv -v "Chromium Embedded Framework" "$libpath" &&
    codesign --force --deep --sign "$cert" "$path"

...with the final deep codesign happening at the end. Otherwise moving the hijacked library into `Chromium Embedded Framework.framework` invalidates the app's signature, thus resulting in the crash.

**Comment by r1olo** [comment]
Thank you, it should be fixed now.
