### ISSUE TITLE
Instructions Unclear

### ISSUE THREAD

**Issue by archiefly** [r1olo/spotify-adblock-macos#5]
Hi, Ive been eyeing this for a while but just got round to trying it: I notice the readme instructions have changed and a few older variations are in history. This has left me unclear about what to do. Thank you in advance for clarification.

**Comment by duncannah** [comment]
First, you need to create a certificate as shown [here](https://support.apple.com/en-om/guide/keychain-access/kyca8916/mac), the certificate type being "code signing".

And then you run the command shown in the README, while referencing the name of the new certificate, as such:

![Image 2022-01-09 5 PM-04-24](https://user-images.githubusercontent.com/38371914/148690371-cb1df24c-2613-45ff-a205-800a2faecad7.png)

**Comment by archiefly** [comment]
Thank you, I've got it working now. Appreciate the help :)
